version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: fix(deps)
      include: scope
  - package-ecosystem: github-actions
    directory: /.github
    schedule:
      interval: daily
    commit-message:
      prefix: fix(deps)
      include: scope
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: fix
      include: scope
