version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "taihen"
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "daily"
    reviewers:
      - "taihen"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "taihen"
