version: "2"
run:
  concurrency: 4
  tests: true
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - gocritic
    - gocyclo
    - godot
    - gosec
    - misspell
    - nakedret
    - noctx
    - prealloc
    - revive
    - unconvert
    - unparam
    # - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
