version: '3.8'
services:
  mcp-ripestat:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ['8080:8080']
    environment: [PORT=8080]
    restart: unless-stopped
    healthcheck:
      test: [CMD, wget, --spider, -q, 'http://localhost:8080/status']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes: ['./logs:/app/logs']
