name: 'Setup Go Environment'
description: 'Checkout code and setup Go'
inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.24'
  fetch-depth:
    description: 'Checkout fetch depth'
    required: false
    default: '1'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}